docker_image: null
apptainer_image: /clusterfs/nvme/hph/env_images/finetune_develop_torch_25_08.sif

# No need to change anything below
# --------------------------------------------------------------------------------
repo_path: ${oc.env:REPO_DIR}
platform_repo_path: ${oc.env:PLATFORM_REPO_DIR}
data_path: /clusterfs/nvme/segment_4d
server_folder_path: /clusterfs/vast/Data/cell_observatory_training_datasets
synthetic_server_folder_path: /clusterfs/vast/forsynthetic/benchmark_tests/data/synthetic_data_iteration_1
workdir: /workspace/${oc.env:REPO_NAME} # mapping your repo path to this path inside the container
platform_workdir: /workspace/${oc.env:PLATFORM_REPO_NAME} # mapping your platform repo path to this path inside the container

# Relative paths will be updated in manager.py based on the running environment
ray_script: ${oc.env:REPO_DIR}/cluster/ray_local_cluster.sh
runner_script: ${oc.env:PLATFORM_REPO_DIR}/training/runner.py
dotenv_path: ${oc.env:REPO_DIR}/.env

# Keep them null to be set automatically or change in the main config file
# --------------------------------------------------------------------------------
resume_checkpointdir: null
pretrained_checkpointdir: null
outdir: null
