docker_image: ghcr.io/chanzuckerberg/gc-base:25.08-py3-2fad7d6
apptainer_image: null

# No need to change anything below
# --------------------------------------------------------------------------------
repo_path: ${oc.env:REPO_DIR}
data_path: /workspace/CellObservatoryData/hph
server_folder_path: /workspace/CellObservatoryData/data/gokul-lab
workdir: /work/${oc.env:REPO_NAME} # mapping your repo path to this path inside the container

# Relative paths will be updated in manager.py based on the running environment
ray_script: /work/${oc.env:REPO_NAME}/cluster/ray_local_cluster.sh
runner_script: /work/${oc.env:REPO_NAME}/training/runner.py
dotenv_path: /workspace/CellObservatoryData/hph/.env_finetune

pvc_data_name: project-cell-observatory-pvc-120t
pvc_data_mount_path: /workspace/CellObservatoryData

tmpdir: /work/tmp
python_path: /work:/work/cell_observatory_platform

# Keep them null to be set automatically or change in the main config file
# --------------------------------------------------------------------------------
resume_checkpointdir: null
pretrained_checkpointdir: null
outdir: null